# fonts
font_family		Share Tech Mono
bold_font		auto
italic_font		auto
bold_italic_font	auto
font_size		9.0
font_features		none

# cursor
cursor_shape		underline
cursor_shape_unfocused	unchanged
cursor_blink_interval	0.5
cursor_stop_blinking_after	10.0

# colors
background		#0b0c10
foreground		#f4f4f5
cursor			#ff1744
cursor_text_color	#0b0c10
selection_background	#4a1828
selection_foreground	#ffffff
url_color		#ff526f

active_border_color	#ff1744
inactive_border_color	#555861

color0			#0b0c10
color1			#ff1744
color2			#d7d8dc
color3			#b9bbc1
color4			#9699a2
color5			#ff0055
color6			#e6e7ea
color7			#ffffff
color8			#373941
color9			#ff526f
color10			#ededee
color11			#d8d9dd
color12			#b9bbc1
color13			#ff4d8d
color14			#ffffff
color15			#ffffff

# scrollbar
scrollback_lines	1000

# mouse
mouse_hide_wait		5.0
open_url_with		vivaldi
url_color		#ff0000
url_style		curly
detect_urls		yes
paste_actions		no-op
copy_on_select		yes
